osx_image: xcode8
language: objective-c
xcode_project: ExtPlaneSockets.xcodeproj
before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap --platform ios --no-use-binaries
after_success:
  - bash <(curl -s https://codecov.io/bash)
